server:
  port: 8080
  servlet:
    context-path: /api
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:famintos;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverclassname: org.h2.Driver
    username: admin
    password: admin
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
